"""add defaults to user timestamps

Revision ID: f7f339ad748f
Revises: d8ab08acd119
Create Date: 2026-02-19 17:00:58.884595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7f339ad748f'
down_revision: Union[str, Sequence[str], None] = 'd8ab08acd119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) Ensure server default exists for updated_at (so new inserts get a value)
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
    )

    # (created_at already has now() default in your DB per existing_server_default)
    # But keeping this is harmless + explicit
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
    )

    # 2) Backfill NULLs on existing data
    op.execute("UPDATE users SET created_at = now() WHERE created_at IS NULL;")
    op.execute("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL;")

    # 3 Enforcing NOT NULL safely
    op.alter_column(
        'users', 
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    op.alter_column(
        'users', 
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'users', 
        'updated_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        server_default=None,
    )

    op.alter_column(
        'users', 
        'created_at',
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        server_default=None,
    )
    # ### end Alembic commands ###
